/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeekerSignupRouteImport } from './routes/seeker-signup'
import { Route as SeekerLoginRouteImport } from './routes/seeker-login'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealerSignupRouteImport } from './routes/healer-signup'
import { Route as HealerRouteImport } from './routes/healer'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealerSettingsRouteImport } from './routes/healer.settings'
import { Route as HealerProfileRouteImport } from './routes/healer.profile'
import { Route as HealerEventsRouteImport } from './routes/healer.events'
import { Route as HealerEarningsRouteImport } from './routes/healer.earnings'
import { Route as HealerDashboardRouteImport } from './routes/healer.dashboard'
import { Route as HealerBookingsRouteImport } from './routes/healer.bookings'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated.users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedSeekersRouteImport } from './routes/_authenticated.seekers'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated.reviews'
import { Route as AuthenticatedRevenueRouteImport } from './routes/_authenticated.revenue'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated.products'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated.offers'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedModalitiesRouteImport } from './routes/_authenticated.modalities'
import { Route as AuthenticatedHealersRouteImport } from './routes/_authenticated.healers'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated.events'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated.categories'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated.bookings'
import { Route as AuthenticatedUsersIdRouteImport } from './routes/_authenticated.users.$id'
import { Route as AuthenticatedHealersIdRouteImport } from './routes/_authenticated.healers.$id'
import { Route as AuthenticatedBookingsIdRouteImport } from './routes/_authenticated.bookings.$id'

const SeekerSignupRoute = SeekerSignupRouteImport.update({
  id: '/seeker-signup',
  path: '/seeker-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SeekerLoginRoute = SeekerLoginRouteImport.update({
  id: '/seeker-login',
  path: '/seeker-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealerSignupRoute = HealerSignupRouteImport.update({
  id: '/healer-signup',
  path: '/healer-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const HealerRoute = HealerRouteImport.update({
  id: '/healer',
  path: '/healer',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealerSettingsRoute = HealerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HealerRoute,
} as any)
const HealerProfileRoute = HealerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HealerRoute,
} as any)
const HealerEventsRoute = HealerEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => HealerRoute,
} as any)
const HealerEarningsRoute = HealerEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => HealerRoute,
} as any)
const HealerDashboardRoute = HealerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HealerRoute,
} as any)
const HealerBookingsRoute = HealerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => HealerRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSeekersRoute = AuthenticatedSeekersRouteImport.update({
  id: '/seekers',
  path: '/seekers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRevenueRoute = AuthenticatedRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModalitiesRoute = AuthenticatedModalitiesRouteImport.update({
  id: '/modalities',
  path: '/modalities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHealersRoute = AuthenticatedHealersRouteImport.update({
  id: '/healers',
  path: '/healers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIdRoute = AuthenticatedUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedHealersIdRoute = AuthenticatedHealersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedHealersRoute,
} as any)
const AuthenticatedBookingsIdRoute = AuthenticatedBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/healer': typeof HealerRouteWithChildren
  '/healer-signup': typeof HealerSignupRoute
  '/login': typeof LoginRoute
  '/seeker-login': typeof SeekerLoginRoute
  '/seeker-signup': typeof SeekerSignupRoute
  '/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRoute
  '/healers': typeof AuthenticatedHealersRouteWithChildren
  '/modalities': typeof AuthenticatedModalitiesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/products': typeof AuthenticatedProductsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/seekers': typeof AuthenticatedSeekersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/healer/bookings': typeof HealerBookingsRoute
  '/healer/dashboard': typeof HealerDashboardRoute
  '/healer/earnings': typeof HealerEarningsRoute
  '/healer/events': typeof HealerEventsRoute
  '/healer/profile': typeof HealerProfileRoute
  '/healer/settings': typeof HealerSettingsRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/healers/$id': typeof AuthenticatedHealersIdRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/healer': typeof HealerRouteWithChildren
  '/healer-signup': typeof HealerSignupRoute
  '/login': typeof LoginRoute
  '/seeker-login': typeof SeekerLoginRoute
  '/seeker-signup': typeof SeekerSignupRoute
  '/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRoute
  '/healers': typeof AuthenticatedHealersRouteWithChildren
  '/modalities': typeof AuthenticatedModalitiesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/products': typeof AuthenticatedProductsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/revenue': typeof AuthenticatedRevenueRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/seekers': typeof AuthenticatedSeekersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/healer/bookings': typeof HealerBookingsRoute
  '/healer/dashboard': typeof HealerDashboardRoute
  '/healer/earnings': typeof HealerEarningsRoute
  '/healer/events': typeof HealerEventsRoute
  '/healer/profile': typeof HealerProfileRoute
  '/healer/settings': typeof HealerSettingsRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/healers/$id': typeof AuthenticatedHealersIdRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/healer': typeof HealerRouteWithChildren
  '/healer-signup': typeof HealerSignupRoute
  '/login': typeof LoginRoute
  '/seeker-login': typeof SeekerLoginRoute
  '/seeker-signup': typeof SeekerSignupRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRouteWithChildren
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/healers': typeof AuthenticatedHealersRouteWithChildren
  '/_authenticated/modalities': typeof AuthenticatedModalitiesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/revenue': typeof AuthenticatedRevenueRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/seekers': typeof AuthenticatedSeekersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/healer/bookings': typeof HealerBookingsRoute
  '/healer/dashboard': typeof HealerDashboardRoute
  '/healer/earnings': typeof HealerEarningsRoute
  '/healer/events': typeof HealerEventsRoute
  '/healer/profile': typeof HealerProfileRoute
  '/healer/settings': typeof HealerSettingsRoute
  '/_authenticated/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/_authenticated/healers/$id': typeof AuthenticatedHealersIdRoute
  '/_authenticated/users/$id': typeof AuthenticatedUsersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/healer'
    | '/healer-signup'
    | '/login'
    | '/seeker-login'
    | '/seeker-signup'
    | '/bookings'
    | '/categories'
    | '/dashboard'
    | '/events'
    | '/healers'
    | '/modalities'
    | '/notifications'
    | '/offers'
    | '/products'
    | '/profile'
    | '/reports'
    | '/revenue'
    | '/reviews'
    | '/seekers'
    | '/settings'
    | '/users'
    | '/healer/bookings'
    | '/healer/dashboard'
    | '/healer/earnings'
    | '/healer/events'
    | '/healer/profile'
    | '/healer/settings'
    | '/bookings/$id'
    | '/healers/$id'
    | '/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/healer'
    | '/healer-signup'
    | '/login'
    | '/seeker-login'
    | '/seeker-signup'
    | '/bookings'
    | '/categories'
    | '/dashboard'
    | '/events'
    | '/healers'
    | '/modalities'
    | '/notifications'
    | '/offers'
    | '/products'
    | '/profile'
    | '/reports'
    | '/revenue'
    | '/reviews'
    | '/seekers'
    | '/settings'
    | '/users'
    | '/healer/bookings'
    | '/healer/dashboard'
    | '/healer/earnings'
    | '/healer/events'
    | '/healer/profile'
    | '/healer/settings'
    | '/bookings/$id'
    | '/healers/$id'
    | '/users/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/healer'
    | '/healer-signup'
    | '/login'
    | '/seeker-login'
    | '/seeker-signup'
    | '/_authenticated/bookings'
    | '/_authenticated/categories'
    | '/_authenticated/dashboard'
    | '/_authenticated/events'
    | '/_authenticated/healers'
    | '/_authenticated/modalities'
    | '/_authenticated/notifications'
    | '/_authenticated/offers'
    | '/_authenticated/products'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/revenue'
    | '/_authenticated/reviews'
    | '/_authenticated/seekers'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/healer/bookings'
    | '/healer/dashboard'
    | '/healer/earnings'
    | '/healer/events'
    | '/healer/profile'
    | '/healer/settings'
    | '/_authenticated/bookings/$id'
    | '/_authenticated/healers/$id'
    | '/_authenticated/users/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HealerRoute: typeof HealerRouteWithChildren
  HealerSignupRoute: typeof HealerSignupRoute
  LoginRoute: typeof LoginRoute
  SeekerLoginRoute: typeof SeekerLoginRoute
  SeekerSignupRoute: typeof SeekerSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seeker-signup': {
      id: '/seeker-signup'
      path: '/seeker-signup'
      fullPath: '/seeker-signup'
      preLoaderRoute: typeof SeekerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeker-login': {
      id: '/seeker-login'
      path: '/seeker-login'
      fullPath: '/seeker-login'
      preLoaderRoute: typeof SeekerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healer-signup': {
      id: '/healer-signup'
      path: '/healer-signup'
      fullPath: '/healer-signup'
      preLoaderRoute: typeof HealerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healer': {
      id: '/healer'
      path: '/healer'
      fullPath: '/healer'
      preLoaderRoute: typeof HealerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healer/settings': {
      id: '/healer/settings'
      path: '/settings'
      fullPath: '/healer/settings'
      preLoaderRoute: typeof HealerSettingsRouteImport
      parentRoute: typeof HealerRoute
    }
    '/healer/profile': {
      id: '/healer/profile'
      path: '/profile'
      fullPath: '/healer/profile'
      preLoaderRoute: typeof HealerProfileRouteImport
      parentRoute: typeof HealerRoute
    }
    '/healer/events': {
      id: '/healer/events'
      path: '/events'
      fullPath: '/healer/events'
      preLoaderRoute: typeof HealerEventsRouteImport
      parentRoute: typeof HealerRoute
    }
    '/healer/earnings': {
      id: '/healer/earnings'
      path: '/earnings'
      fullPath: '/healer/earnings'
      preLoaderRoute: typeof HealerEarningsRouteImport
      parentRoute: typeof HealerRoute
    }
    '/healer/dashboard': {
      id: '/healer/dashboard'
      path: '/dashboard'
      fullPath: '/healer/dashboard'
      preLoaderRoute: typeof HealerDashboardRouteImport
      parentRoute: typeof HealerRoute
    }
    '/healer/bookings': {
      id: '/healer/bookings'
      path: '/bookings'
      fullPath: '/healer/bookings'
      preLoaderRoute: typeof HealerBookingsRouteImport
      parentRoute: typeof HealerRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seekers': {
      id: '/_authenticated/seekers'
      path: '/seekers'
      fullPath: '/seekers'
      preLoaderRoute: typeof AuthenticatedSeekersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/revenue': {
      id: '/_authenticated/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof AuthenticatedRevenueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/modalities': {
      id: '/_authenticated/modalities'
      path: '/modalities'
      fullPath: '/modalities'
      preLoaderRoute: typeof AuthenticatedModalitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/healers': {
      id: '/_authenticated/healers'
      path: '/healers'
      fullPath: '/healers'
      preLoaderRoute: typeof AuthenticatedHealersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$id': {
      id: '/_authenticated/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthenticatedUsersIdRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/healers/$id': {
      id: '/_authenticated/healers/$id'
      path: '/$id'
      fullPath: '/healers/$id'
      preLoaderRoute: typeof AuthenticatedHealersIdRouteImport
      parentRoute: typeof AuthenticatedHealersRoute
    }
    '/_authenticated/bookings/$id': {
      id: '/_authenticated/bookings/$id'
      path: '/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthenticatedBookingsIdRouteImport
      parentRoute: typeof AuthenticatedBookingsRoute
    }
  }
}

interface AuthenticatedBookingsRouteChildren {
  AuthenticatedBookingsIdRoute: typeof AuthenticatedBookingsIdRoute
}

const AuthenticatedBookingsRouteChildren: AuthenticatedBookingsRouteChildren = {
  AuthenticatedBookingsIdRoute: AuthenticatedBookingsIdRoute,
}

const AuthenticatedBookingsRouteWithChildren =
  AuthenticatedBookingsRoute._addFileChildren(
    AuthenticatedBookingsRouteChildren,
  )

interface AuthenticatedHealersRouteChildren {
  AuthenticatedHealersIdRoute: typeof AuthenticatedHealersIdRoute
}

const AuthenticatedHealersRouteChildren: AuthenticatedHealersRouteChildren = {
  AuthenticatedHealersIdRoute: AuthenticatedHealersIdRoute,
}

const AuthenticatedHealersRouteWithChildren =
  AuthenticatedHealersRoute._addFileChildren(AuthenticatedHealersRouteChildren)

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersIdRoute: typeof AuthenticatedUsersIdRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersIdRoute: AuthenticatedUsersIdRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRouteWithChildren
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedHealersRoute: typeof AuthenticatedHealersRouteWithChildren
  AuthenticatedModalitiesRoute: typeof AuthenticatedModalitiesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRevenueRoute: typeof AuthenticatedRevenueRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSeekersRoute: typeof AuthenticatedSeekersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRouteWithChildren,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedHealersRoute: AuthenticatedHealersRouteWithChildren,
  AuthenticatedModalitiesRoute: AuthenticatedModalitiesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRevenueRoute: AuthenticatedRevenueRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSeekersRoute: AuthenticatedSeekersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface HealerRouteChildren {
  HealerBookingsRoute: typeof HealerBookingsRoute
  HealerDashboardRoute: typeof HealerDashboardRoute
  HealerEarningsRoute: typeof HealerEarningsRoute
  HealerEventsRoute: typeof HealerEventsRoute
  HealerProfileRoute: typeof HealerProfileRoute
  HealerSettingsRoute: typeof HealerSettingsRoute
}

const HealerRouteChildren: HealerRouteChildren = {
  HealerBookingsRoute: HealerBookingsRoute,
  HealerDashboardRoute: HealerDashboardRoute,
  HealerEarningsRoute: HealerEarningsRoute,
  HealerEventsRoute: HealerEventsRoute,
  HealerProfileRoute: HealerProfileRoute,
  HealerSettingsRoute: HealerSettingsRoute,
}

const HealerRouteWithChildren =
  HealerRoute._addFileChildren(HealerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HealerRoute: HealerRouteWithChildren,
  HealerSignupRoute: HealerSignupRoute,
  LoginRoute: LoginRoute,
  SeekerLoginRoute: SeekerLoginRoute,
  SeekerSignupRoute: SeekerSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
